### ISSUE TITLE
Support step rollback

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-transaction#67]
This could be as simple as calling a `#rollback` method (if it exists) on each of the steps run so far, in reverse order.

But the question remains: what if a `#rollback` fails?

**Comment by timriley** [comment]
Should we also care about return value of rollbacks? Would they need to be monadic in the same way as the call functions? Probably not?

**Comment by GustavoCaso** [comment]
Maybe the initial value passed to the transaction ?

**Comment by prikha** [comment]
I would vote for not extending the concept of `Operation` with additional rollback functionality. 

Seems like `Container` could hold something like`RollbackOperation`  and then in `Transaction` we may introduce something like this: 

```rb
require "dry/transaction"

class CreateUser
  include Dry::Transaction

  step :setup_prerequisites, rollback: :rollback_prerequisites
  ...
  step :persist

  def persist(input)
    Right(name: input["name"], email: input["email"])
  rescue StandardError => ex
    Left(ex)
  end

  ...

  def setup_prerequisites(input)
    Right(name: input["name"], email: input["email"])
  end

  def rollback_prerequisites(ex)
    ...
    # In my mind it should return Left because of the direction
    # as of we are moving right to left
    Left(ex)
  end
end
```

So every rollback should take `Left(out)`, of the previous rollback. Again I'm not sure about the propagation: should it be left or right. But it will be cool to have result of the previous `rollback`.

Interesting to hear your thoughts on this @timriley @GustavoCaso ?

**Comment by GustavoCaso** [comment]
Currently I'm working on a spike on how this could work. We haven't decided anything in terms of API changes. So any suggestion is welcome. 

Is interesting what you are suggesting. I was thinking maybe instead of declaring what is you rollback step. We can declare a transaction as having the habilita to rollback at the class level.

```ruby
class MyTransaction 
  include Dry::Transaction

  rollback true
  
  Steps definition here 
end 
```

And with this all the step must have its rollback step defined following a convention of name.
What do you think ?

I think having each rollback step accept a `Left`  input makes sense

**Comment by prikha** [comment]
Personally I would not rely on naming conventions unless there is an autoloading mechanism in place. However it could cutoff some of boilerplate code.

Introducing `rollback` behavior at class level would force me to define a rollback on every step. Most of the examples I have in my head require to rollback 1-2 steps out of the chain.

Again `rollback` at class level might save some coding, but looses agility and simplicity. 

PS 
The only thing i'm a bit confused with is what should be the end result. Obviously it should be `Left(out)` of the last rollback. 

But what about block handling

```
 m.failure(:validate) { ... } 
```

Would it be called? or rollback would override this.

**Comment by GustavoCaso** [comment]
Yes you are right forcing the rollback at a class level will probably not make change since there might by steps without rollback. 

:+1:

**Comment by prikha** [comment]
Ok @GustavoCaso mention me if any help needed, I can work on it

**Comment by GustavoCaso** [comment]
@prikha sure, are you in the gitter channel ?

**Comment by DamirSvrtan** [comment]
Hi everyone! 👋First of all, thank you for all of your hard work.

I wanted to ask wether there is currently any work being done on this feature?

**Comment by timriley** [comment]
Hi @DamirSvrtan, nice to hear from you!

There's no work being done on this feature currently. Honestly, I'm not even sure if such a feature should exist, given the number of questions I raised earlier:

> Should we also care about return value of rollbacks? Would they need to be monadic in the same way as the call functions? Probably not?

I feel like leveraging `around` steps in some way may in fact be the better approach here? For complete flexibility this might require us to provide a nested step DSL, but I'd be interested in hearing about your use case in the meantime and working out whether it's something we could help with given the current features.

**Comment by DamirSvrtan** [comment]
Hi @timriley, super nice to hear back from you as well! :) 

I'd add a concern to your list - does rollbacking mean that the operation is going to needs some state? Not sure how to rollback otherwise in certain scenarios.

I will try to describe the scenario in the near future after I see how a certain implementation goes.

The concern around using a transaction is that not all operations have to be tied to one database. An application can write to multiple data sources and then the transaction scenario kind of fails. I have a feeling the transaction scenario is good for simpler cases, for more complex scenarios only rollbacks on operations can help.

**Comment by mengqing** [comment]
Hi @timriley, wondering why this issue is closed. Is there a conclusion / alternative solution to this problem? I know there is an example for wrapping transaction around steps but is looking for a more controlled approach, eg be able to apply logic around each individual steps
